// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'63ce520548131f9b19bbe76cbb9bc048fd1c9f9c5e98c489be3c991275ca1a55'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly ApprovalRequest: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly type: CodecTypes['mongo/string@1']['output'];
      readonly referenceId: CodecTypes['mongo/string@1']['output'];
      readonly organization: CodecTypes['mongo/string@1']['output'];
      readonly submittedBy: CodecTypes['mongo/string@1']['output'];
      readonly submittedAt: CodecTypes['mongo/string@1']['output'];
      readonly priority: CodecTypes['mongo/string@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly comments: CodecTypes['mongo/string@1']['output'] | null;
      readonly assignedTo: CodecTypes['mongo/string@1']['output'] | null;
      readonly dueDate: CodecTypes['mongo/string@1']['output'] | null;
      readonly slaStatus: CodecTypes['mongo/string@1']['output'] | null;
      readonly internalNotes: CodecTypes['mongo/string@1']['output'] | null;
      readonly escalationStatus: CodecTypes['mongo/string@1']['output'] | null;
      readonly escalationDetails: CodecTypes['mongo/string@1']['output'] | null;
    };
    readonly AuditLog: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly timestamp: CodecTypes['mongo/string@1']['output'];
      readonly actorId: CodecTypes['mongo/objectId@1']['output'];
      readonly action: CodecTypes['mongo/string@1']['output'];
      readonly module: CodecTypes['mongo/string@1']['output'];
      readonly entityType: CodecTypes['mongo/string@1']['output'];
      readonly entityId: CodecTypes['mongo/string@1']['output'];
      readonly organizationId: CodecTypes['mongo/string@1']['output'];
      readonly ipAddress: CodecTypes['mongo/string@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly previousValue: CodecTypes['mongo/string@1']['output'] | null;
      readonly newValue: CodecTypes['mongo/string@1']['output'] | null;
    };
    readonly CarbonProject: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly description: CodecTypes['mongo/string@1']['output'];
      readonly organizationId: CodecTypes['mongo/objectId@1']['output'];
      readonly type: CodecTypes['mongo/string@1']['output'];
      readonly location: CodecTypes['mongo/string@1']['output'];
      readonly methodology: CodecTypes['mongo/string@1']['output'];
      readonly estimatedCredits: CodecTypes['mongo/double@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/string@1']['output'];
      readonly updatedAt: CodecTypes['mongo/string@1']['output'];
    };
    readonly CreditBatch: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly projectId: CodecTypes['mongo/objectId@1']['output'];
      readonly vintage: CodecTypes['mongo/string@1']['output'];
      readonly quantity: CodecTypes['mongo/int32@1']['output'];
      readonly creditsAvailable: CodecTypes['mongo/int32@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/string@1']['output'];
    };
    readonly Doc: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly projectId: CodecTypes['mongo/objectId@1']['output'];
      readonly fileName: CodecTypes['mongo/string@1']['output'];
      readonly filePath: CodecTypes['mongo/string@1']['output'];
      readonly uploadedAt: CodecTypes['mongo/string@1']['output'];
    };
    readonly Organization: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly type: CodecTypes['mongo/string@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly subscriptionPlan: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/string@1']['output'];
      readonly updatedAt: CodecTypes['mongo/string@1']['output'];
    };
    readonly OrgSettings: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly organizationId: CodecTypes['mongo/objectId@1']['output'];
      readonly theme: CodecTypes['mongo/string@1']['output'];
      readonly mfaRequired: CodecTypes['mongo/bool@1']['output'];
    };
    readonly SystemAlert: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly priority: CodecTypes['mongo/string@1']['output'];
      readonly title: CodecTypes['mongo/string@1']['output'];
      readonly entity: CodecTypes['mongo/string@1']['output'];
      readonly timestamp: CodecTypes['mongo/string@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
    };
    readonly Transaction: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly creditBatchId: CodecTypes['mongo/objectId@1']['output'];
      readonly buyerId: CodecTypes['mongo/objectId@1']['output'];
      readonly sellerId: CodecTypes['mongo/objectId@1']['output'];
      readonly quantity: CodecTypes['mongo/int32@1']['output'];
      readonly pricePerUnit: CodecTypes['mongo/double@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/string@1']['output'];
      readonly updatedAt: CodecTypes['mongo/string@1']['output'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly passwordHash: CodecTypes['mongo/string@1']['output'];
      readonly organizationId: CodecTypes['mongo/objectId@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly role: CodecTypes['mongo/string@1']['output'] | null;
      readonly refreshToken: CodecTypes['mongo/string@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/string@1']['output'];
      readonly updatedAt: CodecTypes['mongo/string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly ApprovalRequest: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly type: CodecTypes['mongo/string@1']['input'];
      readonly referenceId: CodecTypes['mongo/string@1']['input'];
      readonly organization: CodecTypes['mongo/string@1']['input'];
      readonly submittedBy: CodecTypes['mongo/string@1']['input'];
      readonly submittedAt: CodecTypes['mongo/string@1']['input'];
      readonly priority: CodecTypes['mongo/string@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly comments: CodecTypes['mongo/string@1']['input'] | null;
      readonly assignedTo: CodecTypes['mongo/string@1']['input'] | null;
      readonly dueDate: CodecTypes['mongo/string@1']['input'] | null;
      readonly slaStatus: CodecTypes['mongo/string@1']['input'] | null;
      readonly internalNotes: CodecTypes['mongo/string@1']['input'] | null;
      readonly escalationStatus: CodecTypes['mongo/string@1']['input'] | null;
      readonly escalationDetails: CodecTypes['mongo/string@1']['input'] | null;
    };
    readonly AuditLog: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly timestamp: CodecTypes['mongo/string@1']['input'];
      readonly actorId: CodecTypes['mongo/objectId@1']['input'];
      readonly action: CodecTypes['mongo/string@1']['input'];
      readonly module: CodecTypes['mongo/string@1']['input'];
      readonly entityType: CodecTypes['mongo/string@1']['input'];
      readonly entityId: CodecTypes['mongo/string@1']['input'];
      readonly organizationId: CodecTypes['mongo/string@1']['input'];
      readonly ipAddress: CodecTypes['mongo/string@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly previousValue: CodecTypes['mongo/string@1']['input'] | null;
      readonly newValue: CodecTypes['mongo/string@1']['input'] | null;
    };
    readonly CarbonProject: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly description: CodecTypes['mongo/string@1']['input'];
      readonly organizationId: CodecTypes['mongo/objectId@1']['input'];
      readonly type: CodecTypes['mongo/string@1']['input'];
      readonly location: CodecTypes['mongo/string@1']['input'];
      readonly methodology: CodecTypes['mongo/string@1']['input'];
      readonly estimatedCredits: CodecTypes['mongo/double@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/string@1']['input'];
      readonly updatedAt: CodecTypes['mongo/string@1']['input'];
    };
    readonly CreditBatch: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly projectId: CodecTypes['mongo/objectId@1']['input'];
      readonly vintage: CodecTypes['mongo/string@1']['input'];
      readonly quantity: CodecTypes['mongo/int32@1']['input'];
      readonly creditsAvailable: CodecTypes['mongo/int32@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/string@1']['input'];
    };
    readonly Doc: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly projectId: CodecTypes['mongo/objectId@1']['input'];
      readonly fileName: CodecTypes['mongo/string@1']['input'];
      readonly filePath: CodecTypes['mongo/string@1']['input'];
      readonly uploadedAt: CodecTypes['mongo/string@1']['input'];
    };
    readonly Organization: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly type: CodecTypes['mongo/string@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly subscriptionPlan: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/string@1']['input'];
      readonly updatedAt: CodecTypes['mongo/string@1']['input'];
    };
    readonly OrgSettings: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly organizationId: CodecTypes['mongo/objectId@1']['input'];
      readonly theme: CodecTypes['mongo/string@1']['input'];
      readonly mfaRequired: CodecTypes['mongo/bool@1']['input'];
    };
    readonly SystemAlert: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly priority: CodecTypes['mongo/string@1']['input'];
      readonly title: CodecTypes['mongo/string@1']['input'];
      readonly entity: CodecTypes['mongo/string@1']['input'];
      readonly timestamp: CodecTypes['mongo/string@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
    };
    readonly Transaction: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly creditBatchId: CodecTypes['mongo/objectId@1']['input'];
      readonly buyerId: CodecTypes['mongo/objectId@1']['input'];
      readonly sellerId: CodecTypes['mongo/objectId@1']['input'];
      readonly quantity: CodecTypes['mongo/int32@1']['input'];
      readonly pricePerUnit: CodecTypes['mongo/double@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/string@1']['input'];
      readonly updatedAt: CodecTypes['mongo/string@1']['input'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly passwordHash: CodecTypes['mongo/string@1']['input'];
      readonly organizationId: CodecTypes['mongo/objectId@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly role: CodecTypes['mongo/string@1']['input'] | null;
      readonly refreshToken: CodecTypes['mongo/string@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/string@1']['input'];
      readonly updatedAt: CodecTypes['mongo/string@1']['input'];
    };
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly approval_requests: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly type: { readonly bsonType: 'string' };
                    readonly referenceId: { readonly bsonType: 'string' };
                    readonly organization: { readonly bsonType: 'string' };
                    readonly submittedBy: { readonly bsonType: 'string' };
                    readonly submittedAt: { readonly bsonType: 'string' };
                    readonly priority: { readonly bsonType: 'string' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly comments: { readonly bsonType: readonly ['null', 'string'] };
                    readonly assignedTo: { readonly bsonType: readonly ['null', 'string'] };
                    readonly dueDate: { readonly bsonType: readonly ['null', 'string'] };
                    readonly slaStatus: { readonly bsonType: readonly ['null', 'string'] };
                    readonly internalNotes: { readonly bsonType: readonly ['null', 'string'] };
                    readonly escalationStatus: { readonly bsonType: readonly ['null', 'string'] };
                    readonly escalationDetails: { readonly bsonType: readonly ['null', 'string'] };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'organization',
                    'priority',
                    'referenceId',
                    'status',
                    'submittedAt',
                    'submittedBy',
                    'type',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly audit_logs: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly timestamp: { readonly bsonType: 'string' };
                    readonly actorId: { readonly bsonType: 'objectId' };
                    readonly action: { readonly bsonType: 'string' };
                    readonly module: { readonly bsonType: 'string' };
                    readonly entityType: { readonly bsonType: 'string' };
                    readonly entityId: { readonly bsonType: 'string' };
                    readonly organizationId: { readonly bsonType: 'string' };
                    readonly ipAddress: { readonly bsonType: 'string' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly previousValue: { readonly bsonType: readonly ['null', 'string'] };
                    readonly newValue: { readonly bsonType: readonly ['null', 'string'] };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'action',
                    'actorId',
                    'entityId',
                    'entityType',
                    'ipAddress',
                    'module',
                    'organizationId',
                    'status',
                    'timestamp',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly credit_batches: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly projectId: { readonly bsonType: 'objectId' };
                    readonly vintage: { readonly bsonType: 'string' };
                    readonly quantity: { readonly bsonType: 'int' };
                    readonly creditsAvailable: { readonly bsonType: 'int' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'creditsAvailable',
                    'projectId',
                    'quantity',
                    'status',
                    'vintage',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly organization_settings: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'organizationId'; readonly direction: 1 },
                  ];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly organizationId: { readonly bsonType: 'objectId' };
                    readonly theme: { readonly bsonType: 'string' };
                    readonly mfaRequired: { readonly bsonType: 'bool' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'mfaRequired', 'organizationId', 'theme'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly organizations: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'name'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly type: { readonly bsonType: 'string' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly subscriptionPlan: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'string' };
                    readonly updatedAt: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'name',
                    'status',
                    'subscriptionPlan',
                    'type',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly project_documents: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly projectId: { readonly bsonType: 'objectId' };
                    readonly fileName: { readonly bsonType: 'string' };
                    readonly filePath: { readonly bsonType: 'string' };
                    readonly uploadedAt: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'fileName',
                    'filePath',
                    'projectId',
                    'uploadedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly projects: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly description: { readonly bsonType: 'string' };
                    readonly organizationId: { readonly bsonType: 'objectId' };
                    readonly type: { readonly bsonType: 'string' };
                    readonly location: { readonly bsonType: 'string' };
                    readonly methodology: { readonly bsonType: 'string' };
                    readonly estimatedCredits: { readonly bsonType: 'double' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'string' };
                    readonly updatedAt: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'description',
                    'estimatedCredits',
                    'location',
                    'methodology',
                    'name',
                    'organizationId',
                    'status',
                    'type',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly system_alerts: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly priority: { readonly bsonType: 'string' };
                    readonly title: { readonly bsonType: 'string' };
                    readonly entity: { readonly bsonType: 'string' };
                    readonly timestamp: { readonly bsonType: 'string' };
                    readonly status: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'entity',
                    'priority',
                    'status',
                    'timestamp',
                    'title',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly transactions: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly creditBatchId: { readonly bsonType: 'objectId' };
                    readonly buyerId: { readonly bsonType: 'objectId' };
                    readonly sellerId: { readonly bsonType: 'objectId' };
                    readonly quantity: { readonly bsonType: 'int' };
                    readonly pricePerUnit: { readonly bsonType: 'double' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'string' };
                    readonly updatedAt: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'buyerId',
                    'createdAt',
                    'creditBatchId',
                    'pricePerUnit',
                    'quantity',
                    'sellerId',
                    'status',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly users: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'email'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly email: { readonly bsonType: 'string' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly passwordHash: { readonly bsonType: 'string' };
                    readonly organizationId: { readonly bsonType: 'objectId' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly role: { readonly bsonType: readonly ['null', 'string'] };
                    readonly refreshToken: { readonly bsonType: readonly ['null', 'string'] };
                    readonly createdAt: { readonly bsonType: 'string' };
                    readonly updatedAt: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'email',
                    'name',
                    'organizationId',
                    'passwordHash',
                    'status',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly organizations: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Organization';
    };
    readonly organization_settings: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'OrgSettings';
    };
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly projects: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'CarbonProject';
    };
    readonly project_documents: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Doc';
    };
    readonly credit_batches: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'CreditBatch';
    };
    readonly transactions: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Transaction';
    };
    readonly approval_requests: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'ApprovalRequest';
    };
    readonly audit_logs: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'AuditLog';
    };
    readonly system_alerts: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'SystemAlert';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly ApprovalRequest: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly referenceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly organization: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly submittedBy: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly submittedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly priority: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly comments: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly assignedTo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly dueDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly slaStatus: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly internalNotes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly escalationStatus: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly escalationDetails: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'approval_requests' };
          };
          readonly AuditLog: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly timestamp: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly actorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly action: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly module: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly entityType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly entityId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly organizationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly ipAddress: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly previousValue: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly newValue: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly actor: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['actorId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'audit_logs' };
          };
          readonly CarbonProject: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly organizationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly location: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly methodology: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly estimatedCredits: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly organization: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Organization';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['organizationId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly documents: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Doc';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['projectId'];
                };
              };
              readonly creditBatches: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'CreditBatch';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['projectId'];
                };
              };
            };
            readonly storage: { readonly collection: 'projects' };
          };
          readonly CreditBatch: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly projectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly vintage: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly creditsAvailable: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly project: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'CarbonProject';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['projectId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly transactions: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Transaction';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['creditBatchId'];
                };
              };
            };
            readonly storage: { readonly collection: 'credit_batches' };
          };
          readonly Doc: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly projectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly fileName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly filePath: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly uploadedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly project: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'CarbonProject';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['projectId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'project_documents' };
          };
          readonly Organization: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly subscriptionPlan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly users: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['organizationId'];
                };
              };
              readonly projects: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'CarbonProject';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['organizationId'];
                };
              };
              readonly settings: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'OrgSettings';
                };
                readonly cardinality: '1:1';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['organizationId'];
                };
              };
            };
            readonly storage: { readonly collection: 'organizations' };
          };
          readonly OrgSettings: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly organizationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly theme: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly mfaRequired: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
            };
            readonly relations: {
              readonly organization: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Organization';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['organizationId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'organization_settings' };
          };
          readonly SystemAlert: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly priority: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly entity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly timestamp: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'system_alerts' };
          };
          readonly Transaction: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly creditBatchId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly buyerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly sellerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly pricePerUnit: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly creditBatch: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'CreditBatch';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['creditBatchId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly buyer: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['buyerId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly seller: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['sellerId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'transactions' };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly organizationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly role: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly refreshToken: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly organization: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Organization';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['organizationId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly auditLogs: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'AuditLog';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['actorId'];
                };
              };
              readonly buyerTxs: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Transaction';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['buyerId'];
                };
              };
              readonly sellerTxs: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Transaction';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['sellerId'];
                };
              };
            };
            readonly storage: { readonly collection: 'users' };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
