import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import {
  FileText,
  ShieldAlert,
  Sparkles,
  Download,
  RefreshCw,
  Calendar,
  User,
  ShieldCheck,
  CheckCircle2,
  Clock,
  ChevronRight
} from 'lucide-react';

export default function ExecutiveBriefings() {
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [briefings, setBriefings] = useState([]);
  const [selectedBriefing, setSelectedBriefing] = useState(null);
  const [error, setError] = useState(null);

  const fetchBriefings = async () => {
    setLoading(true);
    setError(null);
    try {
      const token = localStorage.getItem('token');
      const res = await fetch('/api/executive-risk/briefings?limit=15', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (!res.ok) throw new Error('Failed to load executive briefings.');
      const data = await res.json();
      const list = data.data || [];
      setBriefings(list);
      if (list.length > 0 && !selectedBriefing) {
        setSelectedBriefing(list[0]);
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBriefings();
  }, []);

  const handleGenerateBriefing = async () => {
    setGenerating(true);
    setError(null);
    try {
      const token = localStorage.getItem('token');
      const res = await fetch('/api/executive-risk/briefing', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({})
      });
      if (!res.ok) throw new Error('Failed to synthesize AI briefing.');
      const data = await res.json();
      const newBriefing = data.data;
      setBriefings(prev => [newBriefing, ...prev]);
      setSelectedBriefing(newBriefing);
    } catch (err) {
      alert(`Generation error: ${err.message}`);
    } finally {
      setGenerating(false);
    }
  };

  const handleDownloadBriefing = () => {
    if (!selectedBriefing) return;
    const content = `# ${selectedBriefing.title || 'Executive Risk Briefing'}\n` +
      `Date: ${selectedBriefing.createdAt}\n` +
      `Executive Risk Index: ${selectedBriefing.executiveIndex} (${selectedBriefing.executiveSeverity})\n` +
      `Generated By: ${selectedBriefing.generatedBy || 'Executive AI Assistant'}\n\n` +
      `## Executive Summary\n${selectedBriefing.summary || selectedBriefing.sections?.executiveSummary}\n\n` +
      `## Top Risks Assessment\n${selectedBriefing.sections?.topRisksAssessment}\n\n` +
      `## Emerging Risks Outlook\n${selectedBriefing.sections?.emergingRisksOutlook}\n\n` +
      `## ESG Concerns\n${selectedBriefing.sections?.esgConcerns}\n\n` +
      `## Carbon Exposure\n${selectedBriefing.sections?.carbonExposure}\n\n` +
      `## Compliance & Cross-Border\n${selectedBriefing.sections?.complianceExposure}\n\n` +
      `## Critical Decisions & Overdue Actions\n${selectedBriefing.sections?.criticalDecisions}\n\n` +
      `## Recommended Priorities\n${selectedBriefing.sections?.recommendedPriorities}\n`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `executive_briefing_${selectedBriefing.briefingId || Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
  };

  return (
    <div className="p-6 lg:p-8 space-y-8 bg-slate-50 min-h-screen">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 pb-6">
        <div>
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-indigo-600 text-white rounded-lg shadow-sm">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-slate-900">AI Executive Risk Briefings</h1>
              <p className="text-sm text-slate-500">On-demand structured board intelligence synthesized strictly from verified backend ground truth</p>
            </div>
          </div>
        </div>

        <div className="flex items-center space-x-3">
          <button
            onClick={handleGenerateBriefing}
            disabled={generating}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-medium flex items-center transition-colors shadow-sm disabled:opacity-50"
          >
            <Sparkles className={`w-4 h-4 mr-1.5 ${generating ? 'animate-spin' : ''}`} />
            {generating ? 'Synthesizing Briefing...' : 'Synthesize New AI Briefing'}
          </button>
          <Link
            to="/executive-risk"
            className="px-4 py-2 bg-slate-800 hover:bg-slate-900 text-white rounded-lg text-sm font-medium flex items-center transition-colors shadow-sm"
          >
            <ShieldAlert className="w-4 h-4 mr-1.5" /> Risk Dashboard
          </Link>
        </div>
      </div>

      {/* Main Grid: Left Archive Sidebar / Right Active Briefing */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        {/* Archive Sidebar */}
        <div className="lg:col-span-1 bg-white rounded-2xl p-5 border border-slate-200 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <h3 className="text-sm font-bold text-slate-900 uppercase">Briefing Archive</h3>
            <span className="text-xs text-slate-400">{briefings.length} total</span>
          </div>

          {loading ? (
            <div className="py-8 text-center text-xs text-slate-400">Loading history...</div>
          ) : briefings.length === 0 ? (
            <div className="py-8 text-center text-xs text-slate-500">
              No briefings archived. Click &quot;Synthesize New AI Briefing&quot; to create the first briefing.
            </div>
          ) : (
            <div className="space-y-2.5 max-h-[600px] overflow-y-auto pr-1">
              {briefings.map(b => {
                const isSelected = selectedBriefing?.briefingId === b.briefingId;
                return (
                  <button
                    key={b.briefingId}
                    onClick={() => setSelectedBriefing(b)}
                    className={`w-full text-left p-3 rounded-xl border transition-all ${
                      isSelected
                        ? 'bg-indigo-50/80 border-indigo-200 text-indigo-900 shadow-xs'
                        : 'bg-slate-50 border-slate-200/70 hover:bg-slate-100 text-slate-700'
                    }`}
                  >
                    <div className="flex items-center justify-between text-xs mb-1">
                      <span className="font-mono font-medium text-slate-400">
                        {new Date(b.createdAt).toLocaleDateString()}
                      </span>
                      <span className="px-1.5 py-0.5 rounded text-[10px] font-bold uppercase bg-white border border-slate-200">
                        Index {b.executiveIndex?.toFixed(1)}
                      </span>
                    </div>
                    <div className="text-xs font-semibold truncate">{b.title || 'Executive Briefing'}</div>
                  </button>
                );
              })}
            </div>
          )}
        </div>

        {/* Active Briefing Display */}
        <div className="lg:col-span-3 space-y-6">
          {!selectedBriefing ? (
            <div className="bg-white rounded-2xl p-12 text-center border border-slate-200 shadow-sm">
              <FileText className="w-12 h-12 text-slate-300 mx-auto mb-3" />
              <p className="text-sm text-slate-500">Select a briefing from the archive or synthesize a new one.</p>
            </div>
          ) : (
            <div className="bg-white rounded-2xl p-8 border border-slate-200 shadow-sm space-y-6">
              {/* Briefing Header Banner */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-5">
                <div>
                  <h2 className="text-xl font-bold text-slate-900">{selectedBriefing.title}</h2>
                  <div className="flex flex-wrap items-center gap-3 text-xs text-slate-500 mt-2">
                    <span className="flex items-center"><Calendar className="w-3.5 h-3.5 mr-1" /> {new Date(selectedBriefing.createdAt).toLocaleString()}</span>
                    <span className="flex items-center"><User className="w-3.5 h-3.5 mr-1" /> {selectedBriefing.generatedBy || 'Executive AI Assistant'}</span>
                    <span className="font-mono text-slate-400">ID: {selectedBriefing.briefingId}</span>
                  </div>
                </div>

                <button
                  onClick={handleDownloadBriefing}
                  className="px-3.5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg text-xs font-semibold flex items-center transition-colors"
                >
                  <Download className="w-3.5 h-3.5 mr-1.5 text-slate-500" /> Download Markdown
                </button>
              </div>

              {/* Executive Summary Callout */}
              <div className="p-5 bg-gradient-to-r from-indigo-50/70 to-slate-50 rounded-xl border border-indigo-100">
                <h3 className="text-xs font-bold text-indigo-900 uppercase tracking-wider mb-2">Executive Summary Narrative</h3>
                <p className="text-sm text-indigo-950 font-medium leading-relaxed">
                  {selectedBriefing.summary || selectedBriefing.sections?.executiveSummary}
                </p>
              </div>

              {/* Structured Sections */}
              <div className="space-y-6 text-sm text-slate-700 leading-relaxed">
                <div>
                  <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wide border-b border-slate-100 pb-1 mb-2">
                    Top Risks Portfolio Assessment
                  </h4>
                  <p>{selectedBriefing.sections?.topRisksAssessment}</p>
                </div>

                <div>
                  <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wide border-b border-slate-100 pb-1 mb-2">
                    Emerging Risks Outlook (30 - 90 Days)
                  </h4>
                  <p>{selectedBriefing.sections?.emergingRisksOutlook}</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wide border-b border-slate-100 pb-1 mb-2">
                      ESG Exposure & Volatility
                    </h4>
                    <p>{selectedBriefing.sections?.esgConcerns}</p>
                  </div>
                  <div>
                    <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wide border-b border-slate-100 pb-1 mb-2">
                      Carbon Footprint & Grid Exposure
                    </h4>
                    <p>{selectedBriefing.sections?.carbonExposure}</p>
                  </div>
                </div>

                <div>
                  <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wide border-b border-slate-100 pb-1 mb-2">
                    Regulatory & Cross-Border Compliance (CBAM / CSRD)
                  </h4>
                  <p>{selectedBriefing.sections?.complianceExposure}</p>
                </div>

                <div>
                  <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wide border-b border-slate-100 pb-1 mb-2">
                    Critical Decisions & Overdue Actions
                  </h4>
                  <p>{selectedBriefing.sections?.criticalDecisions}</p>
                </div>

                <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
                  <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wide mb-2">
                    Recommended Executive Priorities
                  </h4>
                  <pre className="font-sans text-xs text-slate-800 whitespace-pre-wrap leading-relaxed">
                    {selectedBriefing.sections?.recommendedPriorities}
                  </pre>
                </div>
              </div>

              {/* Footer Traceability */}
              <div className="flex flex-wrap items-center justify-between text-xs text-slate-400 pt-4 border-t border-slate-100">
                <div className="flex items-center space-x-2">
                  <ShieldCheck className="w-4 h-4 text-emerald-500" />
                  <span>Strict Zero-Hallucination Verified &bull; Grounded in Backend DB Ground Truth</span>
                </div>
                <span className="font-mono">Model: {selectedBriefing.modelVersion || 'executive-analyst-v1'}</span>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
